Import numpy library

In [1]:
import numpy as np

Creating some numpy arrays

In [9]:
list1=[2,3,23,53,64,33,52,78]
print(list1)
a=np.array(list1)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[2, 3, 23, 53, 64, 33, 52, 78]
[ 2  3 23 53 64 33 52 78]
(8,)
1
8


In [11]:
b=np.array([[1,2,3,4,8],
            [34,6,26,68,9],
            [6,7,23,31,57]])
print(b)
print(b.shape)
print(b.ndim)
print(b.size)

[[ 1  2  3  4  8]
 [34  6 26 68  9]
 [ 6  7 23 31 57]]
(3, 5)
2
15


In [ ]:
c=np.array([9,24,67,16],dtype=float)
print(c)
print(c.dtype)

[ 9. 24. 67. 16.]
float64


In [14]:
d=np.zeros((4,5))
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
e=np.ones((4,5))
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
f=np.full((3,5),24)
print(f)

[[24 24 24 24 24]
 [24 24 24 24 24]
 [24 24 24 24 24]]


In [20]:
g=np.eye((6))
print(g)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Random Matrix generation

In [21]:
h=np.random.random((4,2))
print(h)

[[0.3879509  0.67493308]
 [0.57737019 0.2679509 ]
 [0.35057477 0.09721829]
 [0.83028427 0.34324621]]


In [27]:
i=np.random.randint(10,100,(3,5))
print(i)

[[28 20 63 29 43]
 [58 75 31 45 20]
 [39 21 32 57 57]]


Array with evenly spaced value

In [28]:
a=np.linspace(10,1000,50)
print(a)

[  10.           30.20408163   50.40816327   70.6122449    90.81632653
  111.02040816  131.2244898   151.42857143  171.63265306  191.83673469
  212.04081633  232.24489796  252.44897959  272.65306122  292.85714286
  313.06122449  333.26530612  353.46938776  373.67346939  393.87755102
  414.08163265  434.28571429  454.48979592  474.69387755  494.89795918
  515.10204082  535.30612245  555.51020408  575.71428571  595.91836735
  616.12244898  636.32653061  656.53061224  676.73469388  696.93877551
  717.14285714  737.34693878  757.55102041  777.75510204  797.95918367
  818.16326531  838.36734694  858.57142857  878.7755102   898.97959184
  919.18367347  939.3877551   959.59183673  979.79591837 1000.        ]


In [29]:
b=np.arange(10,30,5)
print(b)

[10 15 20 25]


Analysing a numpy array

In [33]:
x=np.random.randint(1,100,(5,8))
print(x)
print(x.shape)
print(x.dtype)
print(x.ndim)
print(x.size)

[[79 57 29 13 33 39 68 55]
 [95 22 22 88 21 36 35 94]
 [ 8 79 33 88 26 47 11 24]
 [44 79 72 93 69  3 82 48]
 [24 93 65 35 88 51  4 26]]
(5, 8)
int32
2
40


Transpose of a matrix

In [36]:
a=np.random.randint(1,1000,(6,4))
print(a)
print(a.shape)
print(a.ndim)
print(a.T)
print(a.T.shape)
print(a.ndim)
b=np.transpose(a)
print(b)
print(b.shape)
print(b.ndim)


[[665 340 532 433]
 [937 529 884 835]
 [438 824 169 950]
 [398 501 427 425]
 [868 236 233 849]
 [330 483 828 999]]
(6, 4)
2
[[665 937 438 398 868 330]
 [340 529 824 501 236 483]
 [532 884 169 427 233 828]
 [433 835 950 425 849 999]]
(4, 6)
2
[[665 937 438 398 868 330]
 [340 529 824 501 236 483]
 [532 884 169 427 233 828]
 [433 835 950 425 849 999]]
(4, 6)
2


Reshaping a array

In [43]:
x=np.random.randint(10,50,(6,7))
print(x)
print(x.shape)
y=x.reshape(7,6)
print(y)
print(y.shape)

[[10 47 24 16 16 48 26]
 [34 18 13 38 32 35 39]
 [35 46 36 49 26 12 36]
 [48 48 44 29 41 45 29]
 [16 41 25 25 14 10 11]
 [26 26 13 45 12 28 31]]
(6, 7)
[[10 47 24 16 16 48]
 [26 34 18 13 38 32]
 [35 39 35 46 36 49]
 [26 12 36 48 48 44]
 [29 41 45 29 16 41]
 [25 25 14 10 11 26]
 [26 13 45 12 28 31]]
(7, 6)


Mathematical operation with numpy arrays

In [40]:
a=np.random.randint(20,50,(3,4))
b=np.random.randint(10,100,(3,4))

print(a)
print(a+5)
print(b)

#addition
print(a+b)
#subtraction
print(a-b)
#division
print(a/b)
#multiplication
print(a*b)

[[29 25 41 31]
 [46 28 44 33]
 [24 49 26 49]]
[[34 30 46 36]
 [51 33 49 38]
 [29 54 31 54]]
[[55 23 22 44]
 [77 80 78 53]
 [79 15 60 28]]
[[ 84  48  63  75]
 [123 108 122  86]
 [103  64  86  77]]
[[-26   2  19 -13]
 [-31 -52 -34 -20]
 [-55  34 -34  21]]
[[0.52727273 1.08695652 1.86363636 0.70454545]
 [0.5974026  0.35       0.56410256 0.62264151]
 [0.30379747 3.26666667 0.43333333 1.75      ]]
[[1595  575  902 1364]
 [3542 2240 3432 1749]
 [1896  735 1560 1372]]


In [1]:
import numpy as np

In [6]:
var=np.arange(1,100,4)
print(var)
var

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]


array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [14]:
var=np.matrix([[2,4,7],
               [3,6,2],
               [5,2,8]])
var

matrix([[2, 4, 7],
        [3, 6, 2],
        [5, 2, 8]])

In [15]:
print(var.sum(axis=0))
print(var.sum(axis=1))

[[10 12 17]]
[[13]
 [11]
 [15]]


In [16]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [17]:
arr[3]

array([19, 20, 21, 22, 23, 24])

In [ ]:
arr[2:4,1:3]#clicing

array([[14, 15],
       [20, 21]])

In [22]:
arr[2:5,4:6]

array([[17, 18],
       [23, 24],
       [29, 30]])

In [23]:
arr[:,5:6]

array([[ 6],
       [12],
       [18],
       [24],
       [30]])

In [24]:
bool_index=arr%2==0
bool_index


array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [25]:
arr[bool_index]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [30]:
A=np.arange(1,10).reshape(3,3)
B=np.arange(11,20).reshape(3,3)
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [31]:
print(np.dot(A,B))

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [32]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

stacking of array

In [33]:
a=np.arange(1,10)
b=np.arange(11,20)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [34]:
np.vstack((a,b))#vertical stack

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [35]:
np.hstack((a,b))#horizontal stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [36]:
np.column_stack((a,b))

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

Splitting a array:

In [46]:
var=np.arange(2,22).reshape(5,4)
var

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [47]:
np.hsplit(var,2)#splict var into two part

[array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]]),
 array([[ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]])]

In [48]:
var=np.arange(2,22).reshape(4,5)
var

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [49]:
np.vsplit(var,2)

[array([[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21]])]

In [50]:
np.vsplit(var,4)

[array([[2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21]])]